name: Send Daily Email Alerts

on:
  workflow_dispatch: # Allows manual running
  schedule:
    # Runs at 15:15 UTC every day (11:15 AM Toronto Time EDT)
    - cron: '15 15 * * *'

jobs:
  send-emails:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests firebase-admin

      - name: Run email sender script
        env:
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: python send_emails.py
