name: Scrape Gas Prices (DIAGNOSTIC RUN)

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Playwright and its dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          python -m playwright install --with-deps

      - name: Run diagnostic scraper
        # We add '|| true' so the workflow doesn't stop on the expected error
        run: python scraper.py || true

      - name: Upload diagnostic artifacts
        # This is the corrected line, using v4
        uses: actions/upload-artifact@v4
        with:
          name: debug-files
          path: debug_artifacts/
