name: Authentication Test

on:
  workflow_dispatch:

jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Create a test file
        run: echo "Authentication test successful at $(date)" > test-file.txt

      - name: Commit and push the test file
        run: |
          git config --global user.name "Auth Test Bot"
          git config --global user.email "actions@github.com"
          git add test-file.txt
          git commit -m "Test: Add authentication test file"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
